version: "3"

services:
  lwt:
    image: ghcr.io/fertkir/lwt:main
    restart: unless-stopped
    ports:
      - "8080:80"
  db:
    image: mariadb:10.11
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
volumes:
  db: